### ISSUE TITLE
kubernetes-events-printer fails with parse error: Invalid numeric literal at line 1, column 5

### ISSUE THREAD

**Issue by wombat** [kayrus/elk-kubernetes#20]
I tried to install es5 etc but it fails with the following watch log:

```
~/git/kayrus/elk-kubernetes/es5$ ./deploy.sh --watch
Error from server (AlreadyExists): namespaces "monitoring" already exists
Labeling nodes which will serve Elasticsearch data pods
node "node-01.kube.example.com" not labeled
node "node-02.kube.example.com" not labeled
node "node-03.kube.example.com" not labeled
deployment "es-data" created
service "cerebro" created
deployment "cerebro-v0" created
deployment "es-client" created
deployment "es-curator" created
service "elasticsearch-discovery" created
configmap "es-env" created
daemonset "fluentd-elasticsearch" created
service "kibana" created
deployment "kibana-v5" created
deployment "es-master" created
service "elasticsearch-logging" created
deployment "kubernetes-events-printer" created
configmap "es-config" created
configmap "fluentd-config" created
NAME                                        READY     STATUS              RESTARTS   AGE
alertmanager-main-0                         2/2       Running             0          5d
alertmanager-main-1                         2/2       Running             0          5d
alertmanager-main-2                         2/2       Running             0          5d
cerebro-v0-1518099659-f03xk                 0/1       ContainerCreating   0          18s
es-curator-287824922-t93c1                  0/1       ContainerCreating   0          16s
grafana-3524315691-z56zq                    2/2       Running             0          23h
kibana-v5-2521480414-9kf73                  0/1       ContainerCreating   0          10s
kubernetes-events-printer-577402123-x62r4   0/1       ContainerCreating   0          5s
node-exporter-3qm27                         1/1       Running             0          23h
node-exporter-6sv0d                         1/1       Running             0          23h
node-exporter-q5829                         1/1       Running             0          23h
prometheus-k8s-0                            2/2       Running             0          5d
prometheus-k8s-1                            2/2       Running             0          5d
prometheus-operator-247007151-s30bh         1/1       Running             0          5d
es-curator-287824922-t93c1   1/1       Running   0         47s
kubernetes-events-printer-577402123-x62r4   1/1       Running   0         38s
kubernetes-events-printer-577402123-x62r4   0/1       Error     0         39s
kubernetes-events-printer-577402123-x62r4   0/1       Error     1         42s
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   1         43s
kubernetes-events-printer-577402123-x62r4   0/1       Error     2         59s
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   2         1m
kubernetes-events-printer-577402123-x62r4   0/1       Error     3         1m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   3         1m
kubernetes-events-printer-577402123-x62r4   0/1       Error     4         2m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   4         2m
cerebro-v0-1518099659-f03xk   0/1       Running   0         2m
cerebro-v0-1518099659-f03xk   1/1       Running   0         3m
kubernetes-events-printer-577402123-x62r4   0/1       Error     5         3m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   5         3m
kibana-v5-2521480414-9kf73   0/1       Running   0         4m
kubernetes-events-printer-577402123-x62r4   0/1       Error     6         6m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   6         6m
kubernetes-events-printer-577402123-x62r4   0/1       Error     7         11m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   7         11m
kubernetes-events-printer-577402123-x62r4   0/1       Error     8         16m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   8         16m
kubernetes-events-printer-577402123-x62r4   0/1       Error     9         21m
kubernetes-events-printer-577402123-x62r4   0/1       CrashLoopBackOff   9         21m
```

**Comment by wombat** [comment]
ok so I fixed it by adding the correct serviceaccount:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-events-printer
  labels:
    component: fluentd
    role: kubernetes-events-printer
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        component: fluentd
        role: kubernetes-events-printer
    spec:
      serviceAccount: kubernetes-events-printer
      containers:
      - name: kubernetes-events-printer
        image: kayrus/kubernetes-events-printer:latest
        imagePullPolicy: Always

```
